//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zLesson02_Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testDB_01Entities : DbContext
    {
        public testDB_01Entities()
            : base("name=testDB_01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> TCustomers { get; set; }
        public virtual DbSet<Order> TOrders { get; set; }
        public virtual DbSet<Product> TProducts { get; set; }
        public virtual DbSet<ProductInOrder> TProductsInOrders { get; set; }
    }
}
